### ISSUE TITLE
Duplicate keys in `conda-forge.yml` confusing migration/version update bot

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/autoawq-feedstock#14]
It looks like the `github` key in `conda-forge.yml` repeats

https://github.com/conda-forge/autoawq-feedstock/blob/7603e0b5d0d1823af78de07de6d94d468cc99a72/conda-forge.yml#L4-L6

https://github.com/conda-forge/autoawq-feedstock/blob/7603e0b5d0d1823af78de07de6d94d468cc99a72/conda-forge.yml#L10

This in turn causes the bot issues when it attempts migrate this feedstock as evidenced by [this CI error]( https://github.com/regro/cf-scripts/actions/runs/10588764367/job/29341804379#step:7:14583 ):

```python
  conda_forge_tick.utils.ContainerRuntimeError: Error running migrate-feedstock in container - error DuplicateKeyError raised:
  'while constructing a mapping', <ruamel.yaml.error.FileMark object at 0x7ff8270bffc0>, 'found duplicate key "github" with value "{}" (original value: "{}")', <ruamel.yaml.error.FileMark object at 0x7ff831ee30c0>, '
                      To suppress this check see:
                          http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys
                      ', '                    Duplicate keys will become an error in future releases, and are errors
                      by default when using the new API.
                      '
```

Would it be possible to deduplicate these?

**Comment by jakirkham** [comment]
Also looks like the automerge bot request added this bug: https://github.com/conda-forge/autoawq-feedstock/pull/10

cc @beckermr (for awareness)

**Comment by beckermr** [comment]
@jakirkham the bot automerge command did NOT do this. The bug came from a bad merge: https://github.com/conda-forge/autoawq-feedstock/pull/10/commits/f4051a64743271efda72f83b328ba76db4faa2ef

**Comment by jakirkham** [comment]
Ah apologies! Did not see the conflict resolution

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render

**Comment by jakirkham** [comment]
Missed that you already fixed this Matt: https://github.com/conda-forge/autoawq-feedstock/commit/337bf7a648461378c7e11e74f6659c115c556f27

Thank you for your help! 🙏

Closing this out as resolved
